### ISSUE TITLE
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-react-native-module/generators/app/templates/.editorconfig

### ISSUE THREAD

**Issue by suhaotian** [bamlab/generator-react-native-module#5]
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-react-native-module/generators/app/templates/.editorconfig

**Comment by Almouro** [comment]
Hi @suhaotian! Thanks for posting an issue!
Sorry I published the module without realizing that his name in the `package.json` was actually `generator-react-native-android-module`.
`generator-react-native-module` is already taken, so I renamed the module to `generator-module-react-native` and updated the doc! :)

**Comment by suhaotian** [comment]
good job!
